# base image
FROM node:12.2.0-alpine as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install
RUN npm install axios 
RUN npm install react-scripts -g

# set environment variables
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

ADD . /app

# start app
RUN npm run build
